### PR TITLE
Fix click bug

### LINKED ISSUE #174: Touch Punch Click event is triggering
I'm using jquery-2.1.0, jquery-ui-1.10.3.custom and jquery.ui.touch-punch.min 0.2.3. Click event is not triggering in my Ipad device. Please help me

### PR DESCRIPTION
**Pull request by dukex**
Created a new condition to simulate click, now if touchEnd fire less than 500ms of touchStart will call click

Maybe fix #174 #155 #153 #143 #120 #104

### CODE REVIEW

**Comment by Gnafu** [comment]
:+1:
This fixes an issue I had with iPad: click on buttons where not triggered

**Comment by dotpao** [comment]
It is working to me, I had a problem on Android devices. Thanks.
Why is not accepted this pull request?

**Comment by dukex** [comment]
I rebase my branch to remove conflicts!

**Comment by nobitagit** [comment]
I confirm that @dukex is working and solves the issue of click events going dead on mobile.

In my case I had one more issue though. I was still unable to focus on `input`s and `textarea`s in my app (as these are not click events). I forked from your repo and added a quick fix for this too on top of yours. 

I subscribed to this PR so in case this will go through I will submit mine also, if needed.
In the meantime if anyone needs it my fork is [here](https://github.com/nobitagit/jquery-ui-touch-punch).

**Pull request closed without merging**
