### PR TITLE
$.support.touch to support more devices

### PR DESCRIPTION
**Pull request by cbosco**
Great plugin!  Small (important, to me) tweak: I changed $.support.touch to mirror jQuery Mobile.  Yours always returned false for my Android and Blackberry webkit test devices. 

Change $.support.touch to mirror jQuery Mobile and extend rather than override

### CODE REVIEW

**Comment by ghost** [comment]
Love the script. Couldn't believe so little code did so much. I did the same as 'cbosco'. I opened up the available supported browsers with my own code, (I'm not using jQMobile). The problem on my Android 2.2 phone was that (typeof window.Touch === "object") returned false while Touch functionality was still available. So I rolled my own:

```
touch: {
ontouchstart:   (window.hasOwnProperty('ontouchstart') ?    true : false),
ontouchend: (document.hasOwnProperty('ontouchend') ?    true : false),
create:     (document.hasOwnProperty('createTouch') ?   true : false),
create_try: (function () { "use strict"; try { document.createEvent("TouchEvent"); return true; } catch (e) {} return false; }()),
object:     (typeof window.Touch === "object" ?     true : false)
}
```

..and use a majority of true more than false values to decide if Touch is available. This works, but the jQMobile code may be better. I haven't had a look at it yet. So now it all works for me too. Great script. Saved me hours (weeks?) of work. Thanks.

**Comment by cbosco** [comment]
Thanks for the comment mobilesiteos.

The jQuery mobile code is really brief, if you're curious:

```
$.support.touch = 'ontouchend' in document;
```

I like that your code is thorough but not sure about the "majority of true" to decide if touch works.  That said, If my fork doesn't work on Android 2.2 do let me know!

**Comment by ghost** [comment]
Hi cbosco,

Yeah the "majority of true" is because some browsers return true for
some of the tests (not verified by me directly, but from googling)
when in fact Touch is not truly available. So I use a "preponderance"
of evidence approach to determine Touch availablity. That is, false's
count against, while true's count for the availability of Touch. So
even some tests returning true can be outweighed by others returning
false. Sort of a vote up/down thing.

On Mon, Aug 8, 2011 at 9:48 AM, cbosco
reply@reply.github.com
wrote:

**Comment by furf** [comment]
Fixed. Please let me know if the new version is working on Android. I'm iOS only :)

**Pull request closed without merging**
