### PR TITLE
Fixes cascading touch handling, and a mousedown issue

### PR DESCRIPTION
**Pull request by fracmak**
There are two commits, the first one fixes an issue where an internal widget variable isn't being reset because the mousedown event on the document isn't being triggered correctly with some touch events. The second commit prevents cascading touch events from getting accidentally processed (this fixes an issue I was having with a draggable inside a draggable)

### CODE REVIEW

**Comment by pixelass** [comment]
great fix.. Just what I needed.  This just changed touch punch from a "no go" to a "go on"  ;)...

**Comment by fracmak** [comment]
lol. You're script is brilliant in it's simplicity and power. I have one other change that I'm debating whether it's worth submitting as a patch. It falls into the category of "I need it for my project, but it might not be something everyone else wants". The basic change is that I don't allow a mouse down event to proceed if more than 1 finger is down. This kind of falls in line of we're only simulating single mouse clicks, not multi-finger drags. My situation is that I have a section of my webapp that supports pinch zooming, but there are often jquery draggable widgets on top of it, so you can very easily accidentally "catch" a jquery widget while pinch zooming. Another option would be to allow multi-finger drags, but only if both fingers are on the target element. But that doesn't feel right either. Thoughts?

**Comment by furf** [comment]
event.stopPropagation seems to handle the cascading issue without needing preventDefault.

**Comment by fracmak** [comment]
The problem with that is if there's a root handler like the one the
mouse handler uses on the document, it'll miss the event entirely and
you could get weird behavior bugs. The policy of jquery ui is not to
prevent event propagation.

Jay

On Nov 18, 2011, at 7:44 PM, Dave Furfero
reply@reply.github.com
wrote:

**Pull request closed without merging**
