### PR TITLE
Adds AMD support and uses grunt to build minified version

### PR DESCRIPTION
**Pull request by nervetattoo**
This adds support for users of AMD modules by having it register as an anonymous module if a loader is in place. Makes it possible to control which jquery instance that will be monkey patched for the cases where several instances are loaded on one page.

Also adds a `grunt.js` file to assist in linting and building minified version.

### CODE REVIEW

**Comment by raldred** [comment]
Hey Don't suppose you have an example of this working?
I cannot get touch punch to work at all with requireJS

**Comment by nervetattoo** [comment]
It should just be as simple as this @raldred :

``` js
define(['jquery', 'jquery-ui', 'jquery.ui.touch-punch'], function($) {
  // $ will have ui and touch-punch hooked onto itself in this context
});
```

But you need to use my fork or apply the patch yourself as @furf has not merged it or done anything with this PR.

**Comment by jwerre** [comment]
Thank you for this!

**Comment by nichlasbresch** [comment]
Thanks! Exactly what i needed...

**Pull request closed without merging**
